version: '3.4'
services:
  tftpd-hpa:
    image: danrue/tftpd-hpa
    volumes:
      - ./tftp:/srv/tftp:ro
    ports:
      - 69:69/udp
    restart: always
        
volumes:
  tftp:
    name: tftp-filesystem
    
